apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-model-service
  namespace: docket
  labels:
    keel.sh/policy: force
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-model-service
  template:
    metadata:
      labels:
        app: ai-model-service
    spec:
      containers:
      - name: ai-model-service
        image: appsmithvivonk/ai-model-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 11434
        resources:
          limits:
            cpu: "4"
            memory: "8Gi"
          requests:
            cpu: "2"
            memory: "4Gi"