apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-model-service
  namespace: docket
  annotations:
    keel.sh/policy: force
    keel.sh/trigger: poll
    keel.sh/pollSchedule: "@every 10m"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-model-service
  template:
    metadata:
      labels:
        app: ai-model-service
    spec:
      containers:
      - name: ai-model-service
        image: appsmithvivonk/ai-model-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 11434
        resources:
          limits:
            cpu: "8"
            memory: "16Gi"
          requests:
            cpu: "6"
            memory: "12Gi"