name: Master update pipeline

on:
  push:
    branches:
      - master

jobs:
  build-push:
    if: success()
    name: Build and Push Docker Image
    uses: ./.github/workflows/build-push.yaml
    secrets: inherit

  terraform-deploy:
    if: success()
    name: Terraform Deployment
    uses: ./.github/workflows/terraform-deploy.yaml
    secrets: inherit

  k8s-deploy:
    if: success()
    name: Kubernetes Deployment
    needs: [terraform-deploy]
    uses: ./.github/workflows/k8s-deploy.yaml
    secrets: inherit