name: Terraform Deployment

on:
  push:
    branches:
      - master
    paths:
      - 'terraform/**'
      - '.github/workflows/terraform-deploy.yaml'

env:
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

jobs:
  terraform:
    name: Run Terraform
    runs-on: self-hosted

    steps:
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Working directory terraform
        run: |
          cd terraform/
          pwd
          echo "Working directory changed to terraform"

      - name: Terraform Init
        run: |
          pwd
          echo "PWD is $PWD"  
          terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply --auto-approve